### ISSUE TITLE
Installing Intel Library on Docker raises error

### ISSUE THREAD

**Issue by dedreira** [rupertnash/azure-impi-containers#1]
Hi! 

I'm trying to make your example working in my environment, so I register and downloaded the Intel library as you suggest in the Dockerfile but at the installation step (when I'm building the image) it raises this error:

The IA-32 architecture host installation is no longer supported
The product cannot be installed on this system.
Please refer to product documentation for more information.

It's strange because my uname -a command throws this output:

Linux ********* 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

(that was from my VM)

And inside docker:

Linux 13d1f5bb82fa 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Have you ever face this error?

Thanks and Regards

**Comment by rupertnash** [comment]
No, I've never seen that error. Afraid this hasn't been used for 2 years and I no longer have an Azure allocation....

Good luck trying to make it work!

**Comment by dedreira** [comment]
Sorry for keeping this issue open for this time, I forgot about it, I gave up trying to make it work.
